#!/usr/bin/env bun
// Generate src/c2c_rulesync/_js_case.py: the case-insensitive equivalence
// classes of a JavaScript regular expression with the `i` flag and without `u`.
//
// Claude Code runs on Bun, so this script must run under Bun (JavaScriptCore),
// ideally the version Claude Code embeds. Python's re.IGNORECASE folds
// differently (for example it equates "k" with U+212A KELVIN SIGN), so
// src/c2c_rulesync/ignore.py matches case-insensitively with these classes
// instead of the flag.
//
// Usage: bun scripts/gen_js_case_classes.mjs src/c2c_rulesync/_js_case.py

import { writeFileSync } from "node:fs";

function isSurrogate(code) {
  return code >= 0xd800 && code <= 0xdfff;
}

// Characters linked by toUpperCase/toLowerCase are the only candidates for
// case-insensitive equality; group them, then let the regex engine decide.
function candidateGroups() {
  const parent = new Map();
  const find = (code) => {
    while (parent.has(code) && parent.get(code) !== code) {
      code = parent.get(code);
    }
    return code;
  };
  const union = (a, b) => {
    const rootA = find(a);
    const rootB = find(b);
    if (!parent.has(rootA)) parent.set(rootA, rootA);
    if (!parent.has(rootB)) parent.set(rootB, rootB);
    if (rootA !== rootB) parent.set(rootB, rootA);
  };
  for (let code = 0; code <= 0xffff; code += 1) {
    if (isSurrogate(code)) continue;
    const char = String.fromCharCode(code);
    for (const mapped of [char.toUpperCase(), char.toLowerCase()]) {
      for (const unit of mapped) {
        const other = unit.charCodeAt(0);
        if (other !== code && !isSurrogate(other)) union(code, other);
      }
    }
  }
  const groups = new Map();
  for (const code of parent.keys()) {
    const root = find(code);
    if (!groups.has(root)) groups.set(root, []);
    groups.get(root).push(code);
  }
  return [...groups.values()].filter((group) => group.length > 1);
}

function matchesIgnoringCase(a, b) {
  const pattern = `^[\\u${a.toString(16).padStart(4, "0")}]$`;
  return new RegExp(pattern, "i").test(String.fromCharCode(b));
}

function equivalenceClasses() {
  const classes = [];
  for (const group of candidateGroups()) {
    const remaining = [...group].sort((x, y) => x - y);
    while (remaining.length) {
      const first = remaining.shift();
      const members = [first];
      for (const other of [...remaining]) {
        if (matchesIgnoringCase(first, other)) {
          if (!matchesIgnoringCase(other, first)) {
            throw new Error(`asymmetric match ${first} ${other}`);
          }
          members.push(other);
          remaining.splice(remaining.indexOf(other), 1);
        }
      }
      if (members.length > 1) classes.push(members);
    }
  }
  return classes.sort((x, y) => x[0] - y[0]);
}

function pythonEscape(code) {
  return code >= 0x20 && code < 0x7f && code !== 0x22 && code !== 0x5c
    ? String.fromCharCode(code)
    : `\\U${code.toString(16).padStart(8, "0")}`;
}

const output = process.argv[2];
if (!output) {
  throw new Error("usage: bun scripts/gen_js_case_classes.mjs <output.py>");
}
if (typeof Bun === "undefined") {
  throw new Error("run this script with Bun, the runtime Claude Code uses");
}
const classes = equivalenceClasses();
const lines = [
  '"""Case-insensitive equivalence classes of JavaScript regular expressions.',
  "",
  "Generated by scripts/gen_js_case_classes.mjs under Bun " + Bun.version + "; do not edit.",
  "Each string holds characters that match each other under the `i` flag",
  'without the `u` flag.',
  '"""',
  "",
  "CASE_CLASSES: tuple[str, ...] = (",
  ...classes.map((members) => `    "${members.map(pythonEscape).join("")}",`),
  ")",
  "",
];
writeFileSync(output, lines.join("\n"));
console.log(`wrote ${output}: ${classes.length} classes`);
